name: popup_menu_utils

description: 自定义系统PopupMenu (Define a new PopupMenu)

homepage: https://github.com/xunan623

issue_tracker: https://github.com/xunan623/PopupMenuUtils/issues

repository: https://github.com/xunan623/PopupMenuUtils

version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/business_live_menu_copy.png
  - images/business_live_menu_back.png
  - images/business_live_menu_emoji.png
  - images/business_live_menu_forbidden.png
  - images/business_live_menu_reply.png
  - images/business_live_menu_report.png
  - images/business_live_menu_shielding.png
  - images/business_live_menu_zan.png
